@startuml
class Pessoa {
    -Nome: String
    -Sobrenome: String
    -DataNascimento: Date
    -Email: String
    
    +EditarDadosPerfil(): void
    +EditarDadosAnimal(): void
    +AdicionarAnimal(animal: Animal): void
    +RemoverAnimal(animal: Animal): void
}

class Fazendeiro {
    -Telefone: String
    -NumeroFuncionarios: int

    +VisualizarGraficos(): void
    +GerarRelatorios(): void
    +AdicionarFuncionario(funcionario: TrabalhadorRural): void
    +RemoverFuncionario(funcionario: TrabalhadorRural): void
}

class TrabalhadorRural {
    +AtualizarLeite(): void
}

class Fazenda {
    -Nome: String
    -Tamanho: int
}

class Rebanho {
    +NumeroDeIndividuos: int
    +NumeroDeCrias: int
}

class Vacina {
    -NomeVacina: String
    -DataVacina: Date
}

class Localizacao {
    -Cidade: String
    -Estado: String
    -Latitude: float
    -Longitude: float
}

class Animal {
    +ID: String
    +Nome: String
    +Raca: String
    +Idade: int
}


Fazenda "1" <-- "*" Pessoa
Fazenda "1" <-- "*" Rebanho
Animal "*" <-- "*" Vacina
Fazenda "1" <-- "1" Localizacao
Rebanho "*" <-- "*" Animal
Pessoa "1" <|-- "1..*" Fazendeiro
Pessoa "1" <|-- "0.. *" TrabalhadorRural

@enduml
