package com.rural_link.entities.animal;

public enum Raca{
    ANGUS, NELORE, BRAHMAN, BRANGUS, SENEPOL, HEREFORD, OUTRA, SAANEN, TOGGENBURG, MURCIANA, PARDA_ALPINA, BOER, SAVANNA,
    CANINDE, MOXOTO, REPARTIDA, SANTA_INES, MORADA_NOVA, SUFFOLK, BERGAMACIA, HAMPSHIRE_DOWN, LANDRACE, LARGE_WHITE, DUROC,
    PIETRAIN, HAMPSHIRE
}
