package com.rural_link.domain.animal;

public enum Raca{
    ANGUS, NELORE, BRAHMAN, BRANGUS, SENEPOL, HEREFORD, SAANEN, TOGGENBURG, MURCIANA, PARDA, ALPINA, BOER, SANTA_INES,
    MORADA_NOVA, LANDRACE, LARGE_WHITE
}
